export const ELEMENTS = {
    iptNomeCompleto: '#page-deliver > form > fieldset:nth-child(2) > div:nth-child(2) > div:nth-child(1) > input[type=text]',
    iptCPF: '#page-deliver > form > fieldset:nth-child(2) > div:nth-child(2) > div:nth-child(2) > input[type=text]',
    iptEmail: '#page-deliver > form > fieldset:nth-child(2) > div:nth-child(3) > div:nth-child(1) > input[type=email]',
    iptWhatsapp: '#page-deliver > form > fieldset:nth-child(2) > div:nth-child(3) > div:nth-child(2) > input[type=text]',
    iptCEP: '#page-deliver > form > fieldset:nth-child(3) > div:nth-child(2) > div:nth-child(1) > input[type=text]',
    btnBuscarCEP: '#page-deliver > form > fieldset:nth-child(3) > div:nth-child(2) > div:nth-child(2) > input[type=button]',
    iptNumero: '#page-deliver > form > fieldset:nth-child(3) > div:nth-child(4) > div:nth-child(1) > input[type=text]',
    iptComplemento: '#page-deliver > form > fieldset:nth-child(3) > div:nth-child(4) > div:nth-child(2) > input[type=text]',
    btnEntregaMoto: '#page-deliver > form > fieldset:nth-child(4) > ul > li:nth-child(1)',
    btnEntregaBicicleta: '#page-deliver > form > fieldset:nth-child(4) > ul > li:nth-child(2)',
    btnEntregaVan: '#page-deliver > form > fieldset:nth-child(4) > ul > li:nth-child(3)',
    btnFotoCNH: 'input[accept^="image"]',
    btnFinalizarCadastro: '#page-deliver > form > button',
    btnVoltarHome: '#page-deliver > header > a',
    labelImgCNH: '#page-deliver > form > div > img',
    labelConfirmacaoCadastrado: '#swal2-title',
    btnFechar: 'body > div.swal2-container.swal2-center.swal2-backdrop-show > div > div.swal2-actions > button.swal2-confirm.swal2-styled',
    labelSejaParceiro: '#page-home > div > main > h1',
    labelAlertaErroCNH: '#page-deliver > form > span',
    labelCPFInvalido: '.alert-error'
}